#include <stdio.h>

int main() {
    printf("Hello World!\n");
    return 0;
}

// Run this using 
// gcc hello_world.c -o hello
// This calls the GCC (GNU Compiler Collection) to produce a binary file from the C code residing in the 'hello_world.c' file.
// The '-o' flag is used to specify the name of the binary file that gets generated by the compiler. 