AESTHETICS = (
    "minimalist",
    "maximalist",
    "baggy",
    "tight",
    "loose",
    "gorpcore",
    "cottagecore",
    "traditional",
    "formalwear",
    "corporate",
    "avant garde",
    "techwear",
    "solarcore",
    "steampunk",
    "cyberpunk",
    "oversized",
    "streetwear",
)